name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  google_sign_in: ^6.1.4
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  firebase_database: ^10.2.4
  provider: ^6.0.5
  google_fonts: ^5.1.0
  lottie: ^2.5.0
  image_picker: ^1.0.1
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  carousel_slider: ^4.2.1
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
